config/routes.rb
Rails.application.routes.draw do
  root 'images#index'
  resources :images, path: :gallery
  post 'comments', to: 'comments#create'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :image
  validates :nickname, length: { maximum: 15 }
  validates :nickname, presence: true
  validates :content, length: { maximum: 140 }
  validates :content, presence: true
end

app/models/image.rb
class Image < ActiveRecord::Base
  has_many :comments, dependent: :destroy

  validates :name, length: { maximum: 108 }
  validates :name, presence: true
  validates :description, length: { maximum: 500 }

  mount_uploader :file, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # POST /comments
  def create
     @comment = Comment.new(comment_params)

     if @comment.save
       redirect_to :back
     else
       errors = []
       @comment.errors.full_messages.each do |message|
          errors.append message
       end
       flash[:error] = errors

       redirect_to image_path comment_params[:image_id]
     end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:nickname, :content, :image_id)
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  def index
    @images = Image.all
  end

  # GET /images/1
  def show
    @next_image_id = Image.where("id > ?", @image.id).order(id: :asc).first || nil
    @previous_image_id = Image.where("id < ?", @image.id).order(id: :desc).first || nil

    @comment = Comment.new
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  def create
    if !image_params[:file].nil?
      file_type = ".#{image_params[:file].content_type.split('/')[1]}"
      file_name = "#{SecureRandom.urlsafe_base64}#{file_type}"

      image_params[:file].original_filename = file_name
      @image = Image.new(name: image_params[:name],
                         description: image_params[:description],
                         file: image_params[:file])

      if @image.save
        File.open(Rails.root.join('public/images', file_name), 'wb') do |file|
          file.write(image_params[:file].read)
        end

        flash[:notice] = "Image was successfully uploaded."
        redirect_to @image
      else
        render :new
      end
    else
      redirect_to new_image_path
    end
  end

  # PATCH/PUT /images/1
  def update
    if @image.update(image_params)
      redirect_to @image, notice: 'Image was successfully updated.'
    else
      render :edit 
    end
  end

  # DELETE /images/1
  def destroy
    @image.destroy
    redirect_to images_url, notice: 'Image was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:name, :description, :file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<div class="container">
    <%= form_for @image, {:multipart => true} do |f| %>
        <div class="row">
            <% if @image.errors.any? %>
                <div class="col-xs-12">
                    <div id="error_explanation">
                        <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

                        <ul>
                            <% @image.errors.full_messages.each do |message| %>
                                <li><%= message %></li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            <% end %>
        </div>

        <div class="row">
            <div class="col-xs-12">
                <%= f.file_field :file %>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12" style="height:20px;"></div>
        </div>

        <div class="row">
            <div class="col-xs-12">
                <%= f.label :name, 'Title ' %>
            </div>
            <div class="col-xs-12">
                <%= f.text_field :name, size: '50', maxlength: 108 %>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12" style="height:20px;"></div>
        </div>

        <div class="row">
            <div class="col-xs-12">
                <%= f.label 'Description' %>
            </div>
            <div class="col-xs-12">
                <%= f.text_area :description, size: '50x10', maxlength: '500', onkeyup: 'textAreaMaxLength(this);' %>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12" style="height:20px;"></div>
        </div>

        <div class="row">
            <div class="actions">
                <div class="col-xs-12">
                    <%= f.submit 'Upload' %>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<div class="container">
    <div class="row">
        <% @images.each do |i| %>
        <div class="col-xs-3">
          <a href=<%= image_path i.id %> class="thumbnail">
              <img class="centered" src=<%= i.file_url %> alt="" />
          </a>
        </div>
            <% end %>
    </div>
</div>

app/views/images/new.html.erb
<%= render 'form' %>

app/views/images/show.html.erb
<div class="container">

    <!--Pager-->
    <div class="row">
        <div class="col-xs-12">
            <ul class="pager">
                <% if @previous_image_id %>
                    <li>
                    <a href="<%= image_path(@previous_image_id) %>">Previous</a>
                <% else %>
                    <li class="disabled">
                    <a href="#">Previous</a>
                <% end %>

                    </li>

                <li><a href="<%= images_path %>">Gallery</a></li>

                <% if @next_image_id %>
                    <li>
                    <a href="<%= image_path(@next_image_id) %>">Next</a>
                <% else %>
                    <li class="disabled">
                    <a href="#">Next</a>
                <% end %>
                    </li>
            </ul>
        </div>
    </div>

    <!--Image-->
    <div class="row">
        <div class="col-xs-12">
            <h1 class="text-wrap"><%= @image.name %></h1>
        </div>

        <div class="col-xs-12">
            <%= link_to(image_tag(@image.file_url(:large)), @image.file_url) %>
        </div>

        <div class="col-xs-12">
            <span class="text-wrap">
                <%= @image.description %>
            </span>
        </div>
    </div>

    <div class="col-xs-12" style="height:20px;"></div>

    <!--Comments-->
    <div class="row">
        <div class="col-xs-12">
            <h3>Comments:</h3>
        </div>

        <% if @image.comments.any? %>
            <% @image.comments.each do |c| %>
                <div class="col-xs-12">
                    <p class="text-wrap"><strong><%= c.nickname %></strong>: <%= c.content %></p>
                </div>
            <% end %>
        <% else %>
            <div class="col-xs-12">
                Be the first to leave a comment!
            </div>
        <% end %>

        <div class="col-xs-12" style="height:50px;"></div>

        <%= form_for @comment do |f| %>
            <% if flash[:error] %>
                <div class="col-xs-12">
                    <div id="error_explanation">
                        <h2>Your comment could not be saved:</h2>

                        <ul>
                            <% flash[:error].each do |message| %>
                                <li><%= message %></li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            <% end %>

            <div class="col-xs-12">
                <%= f.hidden_field :image_id, value: @image.id %>
                <%= f.text_area :content, size: '75', maxlength: '140', onkeyup: 'textAreaMaxLength(this);' %>
            </div>

            <div class="col-xs-12">
                <%= f.label :nickname, 'Nickname ' %>
            </div>

            <div class="col-xs-12">
                <%= f.text_field :nickname, maxlength: 15 %>
            </div>

            <div class="col-xs-12" style="height:20px;"></div>

            <div class="col-xs-12">
                <div class="actions">
                    <%= f.submit 'Submit' %>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>PhotoApp</title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <link rel="stylesheet" type="text/css" href="assets/custom.css">
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>

    <body>
        <ul id="navbar">
            <li id="navbar"><a class="brand active" href="<%= images_path %>">Photo app!</a></li>
            <li id="navbar"><a href="<%= new_image_path %>">Upload image</span></a></li>

        </ul>

        <div class="container">
            <div class="row">
                <div class="col-xs-12" style="height:20px;"></div>
            </div>
        </div>

        <% if !notice.nil? %>
            <p class="text-center" id="notice"><%= notice %></p>
        <% end %>

        <%= yield %>

    </body>
</html>